[tool.poetry]
name = "kg_data"
version = "1.1.0"
description = "Library to process dumps of knowledge graphs (Wikipedia, DBpedia, Wikidata)"
authors = ["Binh Vu <binh@toan2.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
orjson = "^3.5.2"
tqdm = "^4.60.0"
beautifulsoup4 = "^4.9.3"
cityhash = "^0.2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
